### ISSUE TITLE
average over stratified mean differences in 03-causal-infernence-with...

### ISSUE THREAD

**Issue by tgerke** [r-causal/causal_inference_r_workshop#46]
Can probably be done with a second pivot and summarize. The benefit of this would be that we can show it's equal to the ordinary adjusted lm() estimate

**Comment by malcolmbarrett** [comment]
Shocking opinion ahead: maybe we should just use base R to compare. Sometimes the pivot to do basic math feels like a bit much. `thing$estimate[[1]] - thing$estimate[[1]]` might be better in these cases? Thinking about this with the whole game example, too

**Comment by malcolmbarrett** [comment]
I guess where this would be maybe helpful is the continuous example, but then it wouldn't be identical to `lm()` because it would be in those slides it is categorized

**Comment by malcolmbarrett** [comment]
I realize now you were probably talking about this example, but I can't get it to give me the same answer as `lm()`. Thoughts?

```r
n <- 1000
sim2 <- tibble(
  confounder_1 = rbinom(n, 1, 0.5),
  confounder_2 = rbinom(n, 1, 0.5), 
  
  p_exposure = case_when(
    confounder_1 == 1 & confounder_2 == 1 ~ 0.75,
    confounder_1 == 0 & confounder_2 == 1 ~ 0.9,
    confounder_1 == 1 & confounder_2 == 0 ~ 0.2,
    confounder_1 == 0 & confounder_2 == 0 ~ 0.1,
  ),
  exposure = rbinom(n, 1, p_exposure),
  outcome = confounder_1 + confounder_2 + rnorm(n) 
)

sim2 |>
  group_by(confounder_1, confounder_2, exposure) |>
  summarise(avg_y = mean(outcome)) |>
  pivot_wider(
    names_from = exposure,
    values_from = avg_y,  
    names_prefix = "x_"
  ) |>
  summarise(estimate = x_1 - x_0) 
```

**Comment by LucyMcGowan** [comment]
This is the same as fitting lm in stratified models and then taking the
average of the coefficient I think — or putting all interactions in a
single LM model and then marginalizing (like you do with gcomp)

**Comment by malcolmbarrett** [comment]
Ok we ended up doing this after all. I'm such a naysayer lol
