### ISSUE TITLE
rules for associational flow in DAG slides?

### ISSUE THREAD

**Issue by tgerke** [r-causal/causal_inference_r_workshop#47]
I've given the following 4 rules in the past which help identify when/why an association exists between variables. Not necessary to belabor it in the lectures, but could be a useful touchpoint to understand what dag_paths() is doing under the hood.

1. If no variables are conditioned upon, an association path is blocked when two arrowheads collide at some variable
2. A path that contains a noncollider that has been conditioned upon is blocked
3. A collider that has been conditioned upon does not block a path
4. Conditioning on a descendent of a collider does not block a path

**Comment by malcolmbarrett** [comment]
Yes, I think we need more here. Collider stuff comes later but we can at least mention it here
